-- AUTOGENERATED
return {
  [ "do" ] = {
    bits = 8,
    code = 238,
  },
  tostring = {
    bits = 11,
    code = 2041,
  },
  [ "while" ] = {
    bits = 10,
    code = 1015,
  },
  os = {
    bits = 10,
    code = 1012,
  },
  bit32 = {
    bits = 10,
    code = 1011,
  },
  debug = {
    bits = 12,
    code = 4087,
  },
  [ "return" ] = {
    bits = 7,
    code = 114,
  },
  tonumber = {
    bits = 12,
    code = 4092,
  },
  io = {
    bits = 12,
    code = 4089,
  },
  [ "{" ] = {
    bits = 7,
    code = 115,
  },
  [ "}" ] = {
    bits = 7,
    code = 116,
  },
  [ ":end" ] = {
    bits = 14,
    code = 16382,
  },
  load = {
    bits = 13,
    code = 8187,
  },
  _G = {
    bits = 11,
    code = 2036,
  },
  [ "\"boolean\"" ] = {
    bits = 13,
    code = 8186,
  },
  [ "or" ] = {
    bits = 8,
    code = 243,
  },
  [ "\"table\"" ] = {
    bits = 11,
    code = 2033,
  },
  coroutine = {
    bits = 12,
    code = 4086,
  },
  [ "elseif" ] = {
    bits = 8,
    code = 240,
  },
  [ "false" ] = {
    bits = 9,
    code = 494,
  },
  [ "if" ] = {
    bits = 6,
    code = 51,
  },
  [ "for" ] = {
    bits = 8,
    code = 241,
  },
  [ "until" ] = {
    bits = 13,
    code = 8190,
  },
  [ ".." ] = {
    bits = 7,
    code = 109,
  },
  string = {
    bits = 9,
    code = 498,
  },
  [ ">=" ] = {
    bits = 10,
    code = 1009,
  },
  [ "==" ] = {
    bits = 7,
    code = 112,
  },
  package = {
    bits = 11,
    code = 2039,
  },
  [ ":string" ] = {
    bits = 5,
    code = 21,
  },
  print = {
    bits = 10,
    code = 1014,
  },
  [ ":" ] = {
    bits = 7,
    code = 111,
  },
  [ ")" ] = {
    bits = 4,
    code = 7,
  },
  [ "(" ] = {
    bits = 4,
    code = 6,
  },
  [ "+" ] = {
    bits = 6,
    code = 46,
  },
  [ "*" ] = {
    bits = 8,
    code = 235,
  },
  [ "-" ] = {
    bits = 7,
    code = 108,
  },
  [ "," ] = {
    bits = 3,
    code = 2,
  },
  [ "/" ] = {
    bits = 9,
    code = 490,
  },
  _ENV = {
    bits = 14,
    code = 16383,
  },
  [ "1" ] = {
    bits = 6,
    code = 48,
  },
  [ "0" ] = {
    bits = 6,
    code = 47,
  },
  setmetatable = {
    bits = 11,
    code = 2040,
  },
  [ "2" ] = {
    bits = 7,
    code = 110,
  },
  table = {
    bits = 9,
    code = 499,
  },
  require = {
    bits = 12,
    code = 4090,
  },
  [ "<=" ] = {
    bits = 10,
    code = 1008,
  },
  ipairs = {
    bits = 11,
    code = 2038,
  },
  [ "#" ] = {
    bits = 8,
    code = 234,
  },
  math = {
    bits = 9,
    code = 496,
  },
  [ "\"\"" ] = {
    bits = 10,
    code = 1004,
  },
  [ "then" ] = {
    bits = 6,
    code = 53,
  },
  [ "=" ] = {
    bits = 4,
    code = 9,
  },
  [ "repeat" ] = {
    bits = 13,
    code = 8189,
  },
  getmetatable = {
    bits = 12,
    code = 4088,
  },
  [ ">" ] = {
    bits = 9,
    code = 492,
  },
  pairs = {
    bits = 10,
    code = 1013,
  },
  [ "else" ] = {
    bits = 8,
    code = 239,
  },
  [ "not" ] = {
    bits = 9,
    code = 497,
  },
  [ "in" ] = {
    bits = 9,
    code = 495,
  },
  [ "\"function\"" ] = {
    bits = 12,
    code = 4084,
  },
  [ "~=" ] = {
    bits = 8,
    code = 244,
  },
  [ "<" ] = {
    bits = 9,
    code = 491,
  },
  [ "nil" ] = {
    bits = 8,
    code = 242,
  },
  [ "function" ] = {
    bits = 7,
    code = 113,
  },
  [ "%" ] = {
    bits = 10,
    code = 1006,
  },
  [ ";" ] = {
    bits = 8,
    code = 236,
  },
  [ "end" ] = {
    bits = 5,
    code = 22,
  },
  [ ":name" ] = {
    bits = 2,
    code = 0,
  },
  [ "." ] = {
    bits = 4,
    code = 8,
  },
  pcall = {
    bits = 13,
    code = 8188,
  },
  [ "\"string\"" ] = {
    bits = 10,
    code = 1005,
  },
  [ "true" ] = {
    bits = 9,
    code = 500,
  },
  [ "..." ] = {
    bits = 10,
    code = 1007,
  },
  [ "\"nil\"" ] = {
    bits = 12,
    code = 4085,
  },
  [ "\"number\"" ] = {
    bits = 11,
    code = 2032,
  },
  select = {
    bits = 12,
    code = 4091,
  },
  error = {
    bits = 9,
    code = 493,
  },
  [ "-1" ] = {
    bits = 11,
    code = 2034,
  },
  [ "and" ] = {
    bits = 8,
    code = 237,
  },
  [ "local" ] = {
    bits = 6,
    code = 52,
  },
  [ ":number" ] = {
    bits = 5,
    code = 20,
  },
  [ "[" ] = {
    bits = 6,
    code = 49,
  },
  [ "break" ] = {
    bits = 11,
    code = 2037,
  },
  [ "]" ] = {
    bits = 6,
    code = 50,
  },
  type = {
    bits = 9,
    code = 501,
  },
  _ = {
    bits = 11,
    code = 2035,
  },
  [ "^" ] = {
    bits = 10,
    code = 1010,
  },
}