-- AUTOGENERATED
return {
  string = {
    code = 1008,
    bits = 10,
  },
  [ "-" ] = {
    code = 231,
    bits = 8,
  },
  table = {
    code = 1009,
    bits = 10,
  },
  [ "*" ] = {
    code = 492,
    bits = 9,
  },
  type = {
    code = 1010,
    bits = 10,
  },
  coroutine = {
    code = 4086,
    bits = 12,
  },
  ipairs = {
    code = 2034,
    bits = 11,
  },
  getmetatable = {
    code = 8185,
    bits = 13,
  },
  setmetatable = {
    code = 2040,
    bits = 11,
  },
  [ ";" ] = {
    code = 238,
    bits = 8,
  },
  os = {
    code = 2036,
    bits = 11,
  },
  select = {
    code = 4089,
    bits = 12,
  },
  tonumber = {
    code = 4090,
    bits = 12,
  },
  tostring = {
    code = 4091,
    bits = 12,
  },
  _ = {
    code = 2031,
    bits = 11,
  },
  pcall = {
    code = 4088,
    bits = 12,
  },
  load = {
    code = 8187,
    bits = 13,
  },
  [ "[" ] = {
    code = 48,
    bits = 6,
  },
  [ "/" ] = {
    code = 1001,
    bits = 10,
  },
  [ ":repeat11" ] = {
    code = 2028,
    bits = 11,
  },
  [ "==" ] = {
    code = 110,
    bits = 7,
  },
  [ ":repeat1" ] = {
    code = 18,
    bits = 5,
  },
  [ "<=" ] = {
    code = 1004,
    bits = 10,
  },
  [ ">=" ] = {
    code = 1005,
    bits = 10,
  },
  [ "<" ] = {
    code = 1003,
    bits = 10,
  },
  [ "+" ] = {
    code = 106,
    bits = 7,
  },
  [ ":repeat8" ] = {
    code = 237,
    bits = 8,
  },
  [ ":repeat7" ] = {
    code = 236,
    bits = 8,
  },
  [ "..." ] = {
    code = 1000,
    bits = 10,
  },
  math = {
    code = 2035,
    bits = 11,
  },
  [ ":repeat0" ] = {
    code = 2,
    bits = 3,
  },
  [ ":repeat13" ] = {
    code = 4084,
    bits = 12,
  },
  print = {
    code = 2038,
    bits = 11,
  },
  [ "#" ] = {
    code = 230,
    bits = 8,
  },
  [ "{" ] = {
    code = 113,
    bits = 7,
  },
  [ ":number" ] = {
    code = 17,
    bits = 5,
  },
  [ "~=" ] = {
    code = 245,
    bits = 8,
  },
  [ ":repeat9" ] = {
    code = 493,
    bits = 9,
  },
  require = {
    code = 2039,
    bits = 11,
  },
  [ ":repeat12" ] = {
    code = 2029,
    bits = 11,
  },
  [ "=" ] = {
    code = 21,
    bits = 5,
  },
  [ "function" ] = {
    code = 111,
    bits = 7,
  },
  _G = {
    code = 4085,
    bits = 12,
  },
  [ ":name" ] = {
    code = 0,
    bits = 2,
  },
  [ ":repeat2" ] = {
    code = 19,
    bits = 5,
  },
  [ ":repeat3" ] = {
    code = 46,
    bits = 6,
  },
  [ "}" ] = {
    code = 114,
    bits = 7,
  },
  [ "(" ] = {
    code = 14,
    bits = 5,
  },
  [ "^" ] = {
    code = 2030,
    bits = 11,
  },
  [ "end" ] = {
    code = 50,
    bits = 6,
  },
  io = {
    code = 8186,
    bits = 13,
  },
  [ "," ] = {
    code = 6,
    bits = 4,
  },
  [ ":repeat6" ] = {
    code = 109,
    bits = 7,
  },
  _ENV = {
    code = 16383,
    bits = 14,
  },
  [ "\"\"" ] = {
    code = 998,
    bits = 10,
  },
  [ "or" ] = {
    code = 244,
    bits = 8,
  },
  [ ":string" ] = {
    code = 20,
    bits = 5,
  },
  [ ">" ] = {
    code = 494,
    bits = 9,
  },
  error = {
    code = 1006,
    bits = 10,
  },
  [ "\"string\"" ] = {
    code = 2025,
    bits = 11,
  },
  debug = {
    code = 4087,
    bits = 12,
  },
  [ "\"number\"" ] = {
    code = 2024,
    bits = 11,
  },
  [ "\"boolean\"" ] = {
    code = 8184,
    bits = 13,
  },
  [ "\"nil\"" ] = {
    code = 4083,
    bits = 12,
  },
  [ "\"function\"" ] = {
    code = 4082,
    bits = 12,
  },
  [ "\"table\"" ] = {
    code = 2026,
    bits = 11,
  },
  [ "-1" ] = {
    code = 2027,
    bits = 11,
  },
  [ "2" ] = {
    code = 234,
    bits = 8,
  },
  [ ":end" ] = {
    code = 16382,
    bits = 14,
  },
  [ ":repeat5" ] = {
    code = 108,
    bits = 7,
  },
  [ "%" ] = {
    code = 999,
    bits = 10,
  },
  [ "and" ] = {
    code = 239,
    bits = 8,
  },
  [ "break" ] = {
    code = 2033,
    bits = 11,
  },
  [ "do" ] = {
    code = 240,
    bits = 8,
  },
  [ "else" ] = {
    code = 241,
    bits = 8,
  },
  [ "elseif" ] = {
    code = 495,
    bits = 9,
  },
  [ ":repeat10" ] = {
    code = 1002,
    bits = 10,
  },
  [ "false" ] = {
    code = 496,
    bits = 9,
  },
  [ "for" ] = {
    code = 497,
    bits = 9,
  },
  bit32 = {
    code = 2032,
    bits = 11,
  },
  [ "0" ] = {
    code = 233,
    bits = 8,
  },
  [ "if" ] = {
    code = 51,
    bits = 6,
  },
  [ "in" ] = {
    code = 1007,
    bits = 10,
  },
  [ "local" ] = {
    code = 22,
    bits = 5,
  },
  [ "nil" ] = {
    code = 242,
    bits = 8,
  },
  [ "not" ] = {
    code = 243,
    bits = 8,
  },
  [ ")" ] = {
    code = 15,
    bits = 5,
  },
  [ "repeat" ] = {
    code = 8189,
    bits = 13,
  },
  [ "return" ] = {
    code = 112,
    bits = 7,
  },
  [ "then" ] = {
    code = 52,
    bits = 6,
  },
  [ "true" ] = {
    code = 498,
    bits = 9,
  },
  [ "until" ] = {
    code = 8190,
    bits = 13,
  },
  [ "while" ] = {
    code = 1011,
    bits = 10,
  },
  [ "1" ] = {
    code = 107,
    bits = 7,
  },
  [ "." ] = {
    code = 16,
    bits = 5,
  },
  [ ":" ] = {
    code = 235,
    bits = 8,
  },
  [ "]" ] = {
    code = 49,
    bits = 6,
  },
  package = {
    code = 8188,
    bits = 13,
  },
  [ ".." ] = {
    code = 232,
    bits = 8,
  },
  pairs = {
    code = 2037,
    bits = 11,
  },
  [ ":repeat4" ] = {
    code = 47,
    bits = 6,
  },
}